### ISSUE TITLE
Preserve options when templating

### ISSUE THREAD

**Issue by Jmeyering** [QuickenLoans/uri-template#3]
There are circumstances where I would like to preserve template variables after processing a link. The primary use case would be for displaying uri routes with partially filled options, yet displaying the totality of the options to the end user.

For example.

If I have a template that looks like 

`/events{?product,date,days,seats,before,at,after}`

I may want to "prefill" the product value and provide the end user a link that looks like

`/events?product=10{&date,days,seats,before,at,after}`

Currently this is not an option, but it would be helpful in my circumstance if it were.

If this is something you are interested in, I can put in a PR at some point.

**Comment by pleonasm** [comment]
This is a great idea!

I can definitely look at a PR for this if you'd like to submit one. That being said, the state of the code isn't great, though the unit test suite is pretty robust.

**Comment by Jmeyering** [comment]
I'm cool with closing this, however, could we craft a new release? Thanks so much for merging!

**Comment by pleonasm** [comment]
Sorry that took so long, but 1.1.0 is released. Thanks for the contribution!

**Comment by Jmeyering** [comment]
:+1: Thanks so much!
