### ISSUE TITLE
Explode modifier unsupported

### ISSUE THREAD

**Issue by SMillerDev** [QuickenLoans/uri-template#7]
I'm currently trying to use the explode modifier by doing `/url{?filter*}`
and passing `[ 'filter' => [ 'key' => 'value' ] ]` to this library, this will however give me an error. Am I missing something in the implementation here, or is this modifier not supported?

https://tools.ietf.org/html/rfc6570#section-2.4.2

**Comment by pleonasm** [comment]
Could you provide a full code context? This is definitely supported.

This code works perfectly fine for me:

```php
<?php
use QL\UriTemplate\UriTemplate;

require __DIR__ . '/vendor/autoload.php';

$tpl = new UriTemplate('/url{?filter*}');

echo $tpl->expand([
    'filter' => [
        'key' => 'value',
    ],
]);

// outputs `/url?key=value`
```

**Comment by SMillerDev** [comment]
It seems I mixed up different error messages within my application, making me wrongly assume the error was in the url rendering.
